# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366f38f01f449a14bb5f30b5b29152640ed11d1adf3fe336a851b1589ee20712169f1cb04bedb6f9d445003e5ae49ae0d68f6a277366d8ac047afab6779af2a0

test:
  secret_key_base: deb39accb62fbe3be37aa5d7e42879756f603becac0a5cd5d265b94fd63561c9a02ae204606662233cde57e94cc7399f512d2cf79267d06b0e15f2d3f6396bb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
